### ISSUE TITLE
Cannot clone entry missing project

### ISSUE THREAD

**Issue by ManickaP** [lucassabreu/clockify-cli#104]
I have a history going back several months (using web based GUI) and I tried to clone one of the older entries which doesn't have a project associated. I got:
```
project must be informed
```

I'd really prefer not to use project for ever single entry I log. Is there a way around this in the CLI? Do you plan to allow this in the future?

**Comment by lucassabreu** [comment]
i think there is no workaround right now, but i will try to read the worskspace settings to allow entries without project.

once its done i will report here.

**Comment by lucassabreu** [comment]
hi @ManickaP , i fixed it, now if the workspace does not force you to set a project it will not me required.

also there is a new option/config `allow-incomplete` that enables you to start a time entry without setting required fields, but you have to use `clockify-cli edit current` to complete it before closing or starting a new one.

**Comment by ManickaP** [comment]
Awesome @lucassabreu! Thanks!
