### ISSUE TITLE
Default time when starting being set to 1 Jan 0001

### ISSUE THREAD

**Issue by VeteraNovis** [lucassabreu/clockify-cli#108]
# Issue
When running the command `clockify-cli start` without using the `--when` flag, the start time is defaulting to the 1st of January 0001.

## Command run
`clockify-cli start`

## Output
```
+--------------------------+----------+----------+---------------+---------+-------------+------+
|            ID            |  START   |   END    |      DUR      | PROJECT | DESCRIPTION | TAGS |
+--------------------------+----------+----------+---------------+---------+-------------+------+
| 60f62c7204dd143d38c6cdc2 | 07:43:24 | 09:52:51 | 2562047:47:16 |         |             |      |
+--------------------------+----------+----------+---------------+---------+-------------+------+

```

The start time is always 07:43:24 for some reason, and the end time is set to the current time.  I stopped the log using the browser extension and could see that the start date of the recorded entry was January first 0001.  If I use `--when now` the time log starts correctly.

## Version
Installed via Snap
Version: 0.19.1, Commit: a3e0fb949c917519d58e7412c60fcdbaf5b41c4a, Build At: 2021-07-19T23:20:54Z

## Operating system
Ubuntu 21.04

**Comment by lucassabreu** [comment]
hi @VeteraNovis i will look at it soon, can you just confirm to me if in the interactive mode (flag `--interactive`) this is also happening?

**Comment by lucassabreu** [comment]
@VeteraNovis if you update to 0.19.2 the problem will be solved.
