### ISSUE TITLE
(SCC-ST1005) Incorrectly formatted error string

### ISSUE THREAD

**Issue by lucassabreu** [lucassabreu/clockify-cli#142]
## Description
Error strings follow a set of guidelines to ensure uniformity and good composability. Quoting Go Code Review Comments:

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lucassabreu/clockify-cli/issue/SCC-ST1005/occurrences/](https://deepsource.io/gh/lucassabreu/clockify-cli/issue/SCC-ST1005/occurrences/)

**Comment by adithyanandakumar** [comment]
Can I have a look on this?
