### ISSUE TITLE
Question: is there a way to get the amount of hours per day or week in a workspace?

### ISSUE THREAD

**Issue by rbo** [lucassabreu/clockify-cli#144]
Hi, I have a question: is there a way to get the number of hours per day or week in a workspace? With a go template or something like that. I simply want an overview of the worked hours for the current day? Optional for the whole week. 

Thanks
Robert

**Comment by rbo** [comment]
Or is there a way with clockify cli to print the `duration` and/or `totalTime` of a report:
```json
$ curl -s -H "content-type: application/json" -H "X-Api-Key: $CLOCKIFY_TOKEN" -X POST -d @report.json https://reports.api.clockify.me/v1/workspaces/${CLOCKIFY_WORKSPACE}/reports/summary | jq
{
  "totals": [
    {
      "_id": "",
      "totalTime": 18731,
      "totalBillableTime": 0,
      "entriesCount": 5,
      "totalAmount": 0.0
    }
  ],
  "groupOne": [
    {
      "_id": "xxx",
      "name": "Robert",
      "duration": 18731,
      "nameLowerCase": "robert",
      "amount": 0.0,
      "children": [
        {
          "duration": 18731,
          "amount": 0.0,
          "_id": "xxx",
          "name": "xxx",
          "nameLowerCase": "xxx",
          "color": "#d40000",
          "clientName": "",
          "children": [
            {
              "_id": "xxx",
              "name": "",
              "duration": 18731,
              "amount": 0.0
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by rbo** [comment]
Thanks for providing a work-a-round, that's perfect for me. Sadly I don't have time and a lack of Go knowledge to create a PR.  Perfect situation to learn it, but the time :-(  

Thanks for the great project.

**Comment by lucassabreu** [comment]
hi @rbo i created two new output formats `duration-float` and `duration-formatted` that do print only the sum of time, they will print a output similar to the `complete-interval-work`.

there is a description filter on `clockify-cli reports ...` now that will turn `complete-work` obsolete.

**Comment by rbo** [comment]
@lucassabreu awesome thank you very much. Now it works like charm in my waybar: https://github.com/rbo/dotfiles/blob/main/config/waybar/scripts/clockify.sh :-)

**Comment by lucassabreu** [comment]
awesome, the curl you are doing for "in progress" section, could be changed to this:
```sh
$CLI show current -q > /dev/null && class=running || class=paused
```

than you won't need the curl anymore.

**Comment by rbo** [comment]
@lucassabreu much cleaner: https://github.com/rbo/dotfiles/commit/62f48318911b8c8b2d99fa8560d9dab3f8187b80 - thanks again!
