### ISSUE TITLE
Summary/total hours today

### ISSUE THREAD

**Issue by khenriksson** [lucassabreu/clockify-cli#149]
## Description

A neat feature to add to the `log` command would be to have a footer where the total time for today is calculated, to quickly get a grasp of how much one has worked today.

I found myself in need of this, and implemented as a new command `today`, which can be found [here](https://github.com/khenriksson/clockify-cli/commit/995f54a55ef9ac6c534f621f6ec8f1a64b7ac5d4).

```
foo@bar: ~ clockify-cli today
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
|            ID            |  START   |   END    |   DUR   | PROJECT | TASK |                  TAGS                  |
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
| ffffffffffffffffffffffff | 08:25:44 | 12:21:22 | 3:55:38 | Clockify  |  Meeting   |      |
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
| ffffffffffffffffffffffff | 12:21:22 | 14:10:18 | 1:48:56 | Clockify    |  Coding    |    |
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
| ffffffffffffffffffffffff | 14:10:18 | 15:08:42 | 0:58:24 | Clockify  |  Browsing Reddit    |     |
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
|          TOTAL           | 08:25:44 | 15:08:42 | 6:42:58 |
+--------------------------+----------+----------+---------+---------+------+----------------------------------------+
```

(I created a new printTimeEntries function because most of the functions probably use the same, so adding the footer there was a little bit harder, but that could be done as well.)

**Comment by lucassabreu** [comment]
looks interesting :thinking: 
I was using a bash function with the json format to do that, but it looks like a useful thing to have

**Comment by lucassabreu** [comment]
@khenriksson i changed a little bit the way you did so i didn't had to make a new output function.

in the new releases the total fotter line with the total amount of duration will be printed on the "default" formatted.

i also created two new output formats `duration-float` and `duration-formatted` that do print only the sum of time to help on automations.

**Comment by khenriksson** [comment]
Excellent way of handling it, I checked through the commits and much better than what I could have done! 👏🏼
