### ISSUE TITLE
Better handling of incomplete entries

### ISSUE THREAD

**Issue by panmau** [lucassabreu/clockify-cli#154]
When a timer is already running, using `in` is not possible (which makes sense). 

Therefore the error message should account for that case and be more helpful. Currently the message is: 
`Time entry couldn't be created. Project is either required field or given project is archived. Please change your input or update your workspace settings. (code: 501)
`

CLI output:
```
$ clockify-cli in --interactive
? Choose your project: my project
? Description: 
? Choose your tags: 
? Start: 2022-01-14 12:13:00
? End (leave it blank for empty): 
Time entry couldn't be created. Project is either required field or given project is archived. Please change your input or update your workspace settings. (code: 501)
```

**Comment by lucassabreu** [comment]
hi @panmau, just to confirm if I understood it...
the message you copied is about the time entry being ended, and you are suggesting to improve the message to say that the error is about the ending one and not the one being created, right?

(i am a bit confused about the problem).

**Comment by panmau** [comment]
Sorry that I was a bit unclear:
- I had a timer already started from the web ui. 
- Then I wanted to try out this cli and tried to start a new entry from it. I didn't realize at first that I already had one running.
- The CLI output shows what I did and what error I got (only removed the original project selection)

It seems like this error is only reproducable when you have a timer that was started from the Web UI.
I suggest that if this interaction occurs (if it is detectable?), that it shows a more helpful error message. It would have been helpful for me as a first time user.

**Comment by lucassabreu** [comment]
i was able to reproduce it using the client, basically the API and Web UI allows you to start a time entry that is not valid, but will ask to complete it when you end it.

i think I have an idea to fix it, later today i will try it.

```console
❯ clk in --allow-incomplete
+--------------------------+----------+----------+---------+---------+-------------+------+
|            ID            |  START   |   END    |   DUR   | PROJECT | DESCRIPTION | TAGS |
+--------------------------+----------+----------+---------+---------+-------------+------+
| 61e16f33b4965c78e03cb517 | 09:40:18 | 09:40:19 | 0:00:01 |         |             |      |
+--------------------------+----------+----------+---------+---------+-------------+------+
❯ clk in -i
? Choose your project: my project
? Description: Something
? Choose your tags: 
? Start: 2022-01-14 09:40:41
? End (leave it blank for empty): 
Time entry couldn't be created. Project is either required field or given project is archived. Please change your input or update your workspace settings. (code: 501)
```

**Comment by panmau** [comment]
Ah yes. That's it! I started it as incomplete. How would you solve that for `out`?

**Comment by lucassabreu** [comment]
I will validate the open time entry before asking you so select a project... than you can use `edit current` to fix it

it's the best I can do i think, without cluttering the code/command
