### ISSUE TITLE
Allow relative times

### ISSUE THREAD

**Issue by kuon** [lucassabreu/clockify-cli#165]
When prompted for a start or end time, it would be very useful to be able to enter relative times, like so:

+2:30 (in 2 hours 30 minutes)
-2:30 (2 hours 30 minutes ago)

Numbers greater than 60 should work too, for example, it is very common to specify 1h30 as 90 minutes here. So any plain number should be minutes.

**Comment by lucassabreu** [comment]
@kuon the release v0.36.0 has support for relative time, take a look on the command to see the formats.

if you could look if this attends your needs.
