### ISSUE TITLE
-y for cloning a task

### ISSUE THREAD

**Issue by khenriksson** [lucassabreu/clockify-cli#166]
I very often just clone the same kind of task with the same tags over and over, would it be possible to get a -y that just answers yes to all the follow up questions? Choose your project, Description, Tags, start as default and blank for empty.

**Comment by lucassabreu** [comment]
hi @khenriksson, there is a flag for that, just use `-i=0` and it will work the way you want.

you can use the `clockify-cli config --init` to disable interactive mode by default, and than use `-i` when you want the CLI to ask you things.

**Comment by khenriksson** [comment]
Awesome! Closing this then 👍🏼
