### ISSUE TITLE
Show description of an entry in the report

### ISSUE THREAD

**Issue by ktrns** [lucassabreu/clockify-cli#171]
Hi, 

We are starting to use `clockify-cli` in our team, and I am wondering if there was a way to show the description of an entry in the report table. The tables in your documentation on the main site `https://github.com/lucassabreu/clockify-cli` suggest that the description can be shown, but in my case, I see ID, START, END, DUR, PROJECT, TASK, TAGS. 

I am using this version:  `clockify-cli_0.33.0_Darwin_x86_64`. 

Otherwise, the start was very smooth, thanks a lot for your work! 

Best wishes,
Katrin

**Comment by lucassabreu** [comment]
hi @ktrns i think that is a bug i need to fix.

to show the description run this: ` clockify-cli config show-task false`.

i will look into it to always show the description.

**Comment by ktrns** [comment]
Hi @lucassabreu, 

Thanks so much for the fast response! It works now. 

Have a nice day & thanks again
Katrin

**Comment by lucassabreu** [comment]
@ktrns can you try the version: [0.33.1](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.33.1)?

i believe now it should show task and description.

**Comment by ktrns** [comment]
Dear @lucassabreu - I still owe you the test, it is on my todo. 

I ran into another question, and I hope it is ok for you if I just write it in here: Are multiple workspaces supported? I am trying to switch to a second workspace, but I don't manage. For example: 

```
clockify-cli in project123 desc123 -w workspace2
```

The answer is: 
```
not found (code: 404)
```

Any hint? 

Thanks a lot in advance
Katrin

**Comment by lucassabreu** [comment]
the cli should allow you to change the workspace using `-w` like you did.

i think the client did not find the workspace with the id, or something.

can you run it as `clockify-cli in project123 desc123 -w workspace2 --debug` and copy&paste the trace after that message? than i will be able to find what is missing in the request.

**Comment by lucassabreu** [comment]
@ktrns i am closing this issue for now, if see the problem happening again just open a new issue and i will take a look again.
