### ISSUE TITLE
Allow for marking tasks as done

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#174]
Add to list of available commands under `clockify-cli task` to mark a task as complete. An alternative is to allow `clockify-cli delete` to remove tasks.  This would help remove task clutter and keep tasks in focus. Currently the only way I know how to remove a task is to use the website. 

Thanks for the great cli. Looking forward to using it daily.

**Comment by lucassabreu** [comment]
hi @Mjvolk3 , the new release has a command `task done` that you can use for that, you can also use `task edit --done` to do that.

would be great if you tried it and tell me if that helps .

**Comment by Mjvolk3** [comment]
It works well. Is there a reason it doesn't take flags `-p` and `-n` like `task list`?

**Comment by lucassabreu** [comment]
the `-p` is because i put the project id and task id as arguments, you can't change then so i thought it would be better as arguments instead of flags.

the `-n` is available for `task edit`, it did not work for you @mjvolk3?
