### ISSUE TITLE
USER with id <user_id> doesn't belong to PROJECT with id <project_id> (code: 501)

### ISSUE THREAD

**Issue by Fjanks** [lucassabreu/clockify-cli#200]
I just updated to the latest version and now I get the following error message when I try to start some projects with "clockify-cli in":
USER with id <user_id> doesn't belong to PROJECT with id <project_id> (code: 501)

I tried different projects and I suspect that the error happens when I am a member of a group that has access to the project but it does not happen when my user has direct access to the project. I have also tried different versions of clockify-cli and found that the problem does not exist up to 0.22.0. With all newer versions I get this error.

**Comment by lucassabreu** [comment]
thank you @Fjanks this will help me a lot on fixing the bug

**Comment by lucassabreu** [comment]
I "fixed" the problem on [v0.38.1](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.38.1) @Fjanks , the problem seens to be that the Clockify API is not looking into the groups with access like you said when for the "get tasks" endpoint.

and then the CLI shows the error you reported, in the v0.22.0 there was no prompt for the tasks so thats why it worked.

I was able to reproduce it in my workspace and reported it to Clockity's Team and will updated this issue with the resolution.

until the API is fixed the CLI will act like the project does not have tasks to select, as soon as they fix it the prompt will work as intended again.
