### ISSUE TITLE
clockicy-cli report today not recognizing the current time

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#203]
When I ran `clockicy-cli report today` at 9pm I got a blank report. Then when I ran `clockicy-cli report yesterday` I got the current days report. It is as if there is an internal time config that is different than my machines local time. If I run `$ date` in the the terminal it returns the proper date. I checked to see if I need to configure time somehow and I didn't find anything. Any tips to troubleshoot the issue are much appreciated. Thanks!

**Comment by lucassabreu** [comment]
it may be that the timezone that you have set on clockify.me is different from your machine.

go to https://app.clockify.me/user/settings, and on "Time settings" see if is the right timezone.

the API does the timezone conversion using this setting, so if it is different, than the bug you said may happen.

**Comment by Mjvolk3** [comment]
Trying it out. My setting was off. After I know it works I will close.

**Comment by Mjvolk3** [comment]
Working well now.

**Comment by Mjvolk3** [comment]
I spoke too soon. It is now 10:55 PM in Urbana Illinois. Here are my time settings:k
![image](https://user-images.githubusercontent.com/48566106/180919561-cba6705f-f93e-466a-b282-71a411c0e309.png)
I report today and get nothing.
![image](https://user-images.githubusercontent.com/48566106/180919715-0208d619-6bb9-4a20-b2c6-947a74c6b04e.png)
Reporting yesterday shows the proper output for today.

**Comment by lucassabreu** [comment]
@Mjvolk3 i released a new version with a new flag `log-level`, can you run `cc report today --log-level=info` and add it here?

**Comment by lucassabreu** [comment]
the problem is that when serializing it to the api it was "trying to fix" the timezone to UTC, adding "05:00:00" on the param (`end=2022-07-27T05:00:00Z`), it should not be doing this.

i am fixing it now

**Comment by lucassabreu** [comment]
@Mjvolk3 try it on the new release v0.38.3 and tell me if it is fixed.

**Comment by Mjvolk3** [comment]
Seeing the time is now adjusted. Looks good. Thank you!
```
Version: 0.38.4, Commit: cf49ce2ae725f651de862d6803ab6ca67350c312, Build At: 2022-07-27T10:15:40Z
(base) michaelvolk@M1-MV ~ % cc report today --log-level=info
INFO  2022/07/29 11:32:58 LogRange - First Date Param: 2022-07-29 00:00:00 +0000 UTC | Last Date Param: 2022-07-30 00:00:00 +0000 UTC
INFO  2022/07/29 11:32:58 GetUserTimeEntries - Workspace: 6256d9437ce5da1d06a735fd | User: 6256d9427ce5da1d06a735f4 | In Progress: nil | Description:  | Project: 
INFO  2022/07/29 11:32:59 name: GetUserTimeEntries, method: GET, url: https://api.clockify.me/api/v1/workspaces/6256d9437ce5da1d06a735fd/user/6256d9427ce5da1d06a735f4/time-entries?end=2022-07-30T00%3A00%3A00Z&hydrated=1&page=1&page-size=50&start=2022-07-29T00%3A00%3A00Z, status: 200
INFO  2022/07/29 11:32:59 name: WorkspaceUsers, method: GET, url: https://api.clockify.me/api/v1/workspaces/6256d9437ce5da1d06a735fd/users?page=1&page-size=50, status: 200
```
