### ISSUE TITLE
Create command to report only billable hours

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#210]
Something like `clockify-cli report billable`.

**Comment by lucassabreu** [comment]
hi @Mjvolk3 i created a new flag on the report commands that allow filtering for billable and not billable time entries, it is used like:
```console
clk report last-week --billable
```

it is on release [v0.39.0](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.39.0) take a look to see if it attends your need

**Comment by Mjvolk3** [comment]
Works great! I also see you added `cc report last-week --not-billablel.`
