### ISSUE TITLE
Add clients to projects

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#212]
It is not clear how to assign a client to a project.

**Comment by lucassabreu** [comment]
hi @Mjvolk3 , there is a flag on the `cc project add` called `--client` to assign a cliente when creating the project. 

same of the examples of `cc project add` show how to use it.
https://clockify-cli.netlify.app/en/commands/clockify-cli_project_add/#examples

it that what you are asking about?

**Comment by lucassabreu** [comment]
i will close this issue for now, if that was not what you were looking for please open a new one referencing this one.
