### ISSUE TITLE
Config to supress archive

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#219]
Add a configuration option to supress archived tags, etc.

**Comment by lucassabreu** [comment]
the archived tags are showing on the `in` command @Mjvolk3 ?

**Comment by Mjvolk3** [comment]
Yes they were.

**Comment by lucassabreu** [comment]
@Mjvolk3 i introduced a config `allow-archived-tags`, if it is `true` archived tags will be suggested, if is `false` (or not set), then it won't.

try it on version https://github.com/lucassabreu/clockify-cli/releases/tag/v0.41.0
