### ISSUE TITLE
get project: duration null invalid whenever listing for projects

### ISSUE THREAD

**Issue by DarkCat5501** [lucassabreu/clockify-cli#230]
Whenever i try to list the projects or use any interactive mode that does that,
 it gives me the erro: `get project: duraion null invalid`
![image](https://user-images.githubusercontent.com/34375081/205153562-044d4415-2274-4c0c-9d39-0038be21fb7d.png)

**Comment by lucassabreu** [comment]
hi @DarkCat5501 , can you run it as follows:
```sh
clockify-cli project -i list --log-level debug
```

it will output some logs that may help me to fix the bug.

just review the output for any private information that may show in it before pasting it here.

**Comment by DarkCat5501** [comment]
`> clockify-cli project -i list --log-level=debug

DEBUG 2022/12/01 17:51:54 
name: GetProjects, 
method: GET, 
url: https://api.clockify.me/api/v1/workspaces/{workspaceID}/projects?page=1&page-size=50,
status: 200, 
response: "[{"id":"...","name":"...","hourlyRate":null,"clientId":"...","workspaceId":"...","billable":true,"color":"#3F51B5","estimate":null,"archived":true,"duration":null,"clientName":"...","note":"","costRate":null,"timeEstimate":null,"budgetEstimate":null,"template":false,"public":false}, {... ]" //and more 20 like this
duration null is invalid
github.com/lucassabreu/clockify-cli/api/dto.(*Duration).UnmarshalJSON
	/home/runner/work/clockify-cli/clockify-cli/api/dto/request.go:45
encoding/json.(*decodeState).literalStore
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:871
encoding/json.(*decodeState).value
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:387
encoding/json.(*decodeState).object
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:774
encoding/json.(*decodeState).value
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:373
encoding/json.(*decodeState).array
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:561
encoding/json.(*decodeState).value
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:363
encoding/json.(*decodeState).unmarshal
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/decode.go:180
encoding/json.(*Decoder).Decode
	/opt/hostedtoolcache/go/1.17.13/x64/src/encoding/json/stream.go:73
github.com/lucassabreu/clockify-cli/api.(*client).Do
	/home/runner/work/clockify-cli/clockify-cli/api/httpClient.go:130
github.com/lucassabreu/clockify-cli/api.(*client).paginate
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:562
github.com/lucassabreu/clockify-cli/api.(*client).GetProjects
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:1311
github.com/lucassabreu/clockify-cli/pkg/cmd/project/list.NewCmdList.func1
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/project/list/list.go:97
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
main.execute
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:51
main.main
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:31
runtime.main
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255
runtime.goexit
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581
github.com/lucassabreu/clockify-cli/api.(*client).Do
	/home/runner/work/clockify-cli/clockify-cli/api/httpClient.go:130
github.com/lucassabreu/clockify-cli/api.(*client).paginate
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:562
github.com/lucassabreu/clockify-cli/api.(*client).GetProjects
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:1311
github.com/lucassabreu/clockify-cli/pkg/cmd/project/list.NewCmdList.func1
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/project/list/list.go:97
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
main.execute
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:51
main.main
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:31
runtime.main
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255
runtime.goexit
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581
get projects
github.com/lucassabreu/clockify-cli/api.wrapError
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:248
github.com/lucassabreu/clockify-cli/api.(*client).GetProjects
	/home/runner/work/clockify-cli/clockify-cli/api/client.go:1343
github.com/lucassabreu/clockify-cli/pkg/cmd/project/list.NewCmdList.func1
	/home/runner/work/clockify-cli/clockify-cli/pkg/cmd/project/list/list.go:97
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
main.execute
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:51
main.main
	/home/runner/work/clockify-cli/clockify-cli/cmd/clockify-cli/main.go:31
runtime.main
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255
runtime.goexit
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581`

**Comment by lucassabreu** [comment]
hi the version v0.41.1 should have a fix for this problem, can you try it?

**Comment by DarkCat5501** [comment]
i'm gonna try it right now

**Comment by DarkCat5501** [comment]
it worked just fine!

thank you so much, this tool will help me a lot!

**Comment by thawankeane** [comment]
@lucassabreu I got the same issue for `task list` command, the field `duration` of a `task` can be `null` for some projects.

**Comment by thawankeane** [comment]
Sure, I will do it.
