### ISSUE TITLE
Display n projects with clockify-cli in

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#236]
When using the `clokcify-cli in` command would it be possible to have a configuration for the default number of projects displayed? For my use case I would like all projects displayed. I typically have to run `clokcify-cli project list` prior to time entry to get the whole view.

**Comment by lucassabreu** [comment]
hi @Mjvolk3 you mean in the interactive mode or as a auto completion on terminal?

both should be allowing you to select any non-archived project, but they are paginated, you should be able to type parts of the project name and it should refresh the list using it as a filter.

can you paste a example of the problem?

**Comment by Mjvolk3** [comment]
![image](https://user-images.githubusercontent.com/48566106/207752519-5184547b-b952-4d1c-95e9-f9695e01af6a.png)

I have something like 10 projects and would like to be able to see all of them. This isn't absolutely necessary but it would save me from running the `clockify-cli project list` often.

**Comment by lucassabreu** [comment]
hi @Mjvolk3 , i will create a new config to set how many entries will be shown per page for these type of input.

but just to be clear, you can type a section of the name, id and/or client to filter the projects shown, so using `project ls` is not really necessary .

[![asciicast](https://asciinema.org/a/hmSN3hTIFunG9kxDACvP8h65N.svg)](https://asciinema.org/a/hmSN3hTIFunG9kxDACvP8h65N)

**Comment by lucassabreu** [comment]
hi @Mjvolk3 , in the version [v0.44.0](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.44.0) i created a param `-L` to set the number of entries, or you can change the default using `config init`.

**Comment by Mjvolk3** [comment]
This is great! I tried it out and it is just what I needed.
