### ISSUE TITLE
clockify-cli task add

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#237]
Would it be possible to add a command for task add that is similar to task done? For instance`clockify-cli task -p project_name add task_name` which would follow the pattern `clockify-cli task -p project_name done task_name`. My guess is that this isn't done because task add can be modified with some flags, but this would be nice to quickly bulk add tasks if those flags are not needed. Then like `done` you could add a list of tasks to a project.

**Comment by lucassabreu** [comment]
this could be made into a `quick-add` command that asks from the project as a flag (like the others) and the args are the names of the tasks you wanna create.

it won't support the other options, but if you don't need assignee, billable or a estimation of time to differ from the project, it may be useful.

a `quick-add` would help you?

**Comment by Mjvolk3** [comment]
Yes I would use this often. Would it be possible for the current `add` to default to `quick-add` if there isn't a `-n` ?

**Comment by lucassabreu** [comment]
this would make the code unnecessary complicated i think, but i will work on a quick-add soon

**Comment by lucassabreu** [comment]
hi @Mjvolk3 , `task quick-add` is one version [v0.44.0](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.44.0) can you try it?

**Comment by Mjvolk3** [comment]
@lucassabreu  This works perfectly for me.
