### ISSUE TITLE
Question: Pass CLI return value back to an application

### ISSUE THREAD

**Issue by satikusala** [lucassabreu/clockify-cli#243]
Quick question, is there way to pass back to an application the result of a clockify-cli command? For example, if i have an application, like Tinderbox trigger a command like project list, can the project list be returned back to the application somehow?

**Comment by satikusala** [comment]
BTW, thanks, I figure it out.  Turns out the CLI returns a result that Tinderbox's interface can read. Wickedly cool! Will share video once I have it ready.

**Comment by lucassabreu** [comment]
related to #242
