### ISSUE TITLE
Command to Resume Last Entry?

### ISSUE THREAD

**Issue by NormCopeland** [lucassabreu/clockify-cli#259]
I've reviewed the documentation and so assume this isn't possible but wanted to double check here. Is it possible to resume the last entry without needing to specify the project id? Thanks!

**Comment by lucassabreu** [comment]
hi @NormCopeland , there is a command for that the [`clone`](https://clockify-cli.netlify.app/en/commands/clockify-cli_clone/), to "resume" or clone the last time entry just run:

```sh
clockify-cli clone last
```

**Comment by NormCopeland** [comment]
Thank you! Much appreciated.
