### ISSUE TITLE
Report on a Client without specifying project?

### ISSUE THREAD

**Issue by NormCopeland** [lucassabreu/clockify-cli#260]
hi, I tried to run a report for a client using:
`clockify-cli report this-month -S -F --billable -c xxxxxxxxxxxxxxxxxxx`
but encountered the error:
`flag 'client' can't be used without flag 'project'`

Is there any workaround or method for getting the total billable hours for a client regardless of project?

**Comment by lucassabreu** [comment]
hi @NormCopeland , right now there are no way to filter for the client, but you can get the total for all the projects of a client this way:

```bash
clockify-cli project ls --clients "Client's Name" -q | xargs -I{} clockify-cli report this-month -p {} -D | paste -sd+ | bc
```

**Comment by NormCopeland** [comment]
Thank you! Would you like this issue left open as a future enhancement?

**Comment by lucassabreu** [comment]
yep,leave it open for now

**Comment by lucassabreu** [comment]
hi @NormCopeland can you update the client for the [v0.49.0](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.49.0) version and try the way you tried first?

**Comment by NormCopeland** [comment]
@lucassabreu when I attempt to upgrade via brew it doesn't seem that v0.49.0 is available. I'll attempt a manual upgrade later and let you know.
Thanks!
