### ISSUE TITLE
Add optional client column to report

### ISSUE THREAD

**Issue by tykeal** [lucassabreu/clockify-cli#265]
Our clockify setup has several clients all with similarly named (and colored!) projects. There is no way in with the current report to see which client a given entry is against.

It would be nice if there was a configuration option to also display the client information, ideally something that could be set in the config to always show it.

**Comment by lucassabreu** [comment]
hi @tykeal 

i add i new config `show-client` on the [0.51.0 version](https://github.com/lucassabreu/clockify-cli/releases/tag/v0.51.0).

you can set it using `clockify-cli config set show-client true` or with `clockify-cli config init`.

try it and tell me if it helps you

**Comment by tykeal** [comment]
@lucassabreu ,

Thanks for working on this! It's almost there.

It shows that data that I'm after but the column names aren't correct when it's enabled.

The client data is showing in the `DESCRIPTION` column, the description data is showing in the `TAGS` column and the tags data is showing in an unnamed column when it's turned on.

I would expect that the client data would be titled `CLIENT` and the the other columns to have their titles set correctly as well.

**Comment by tykeal** [comment]
@lucassabreu v0.51.1 works great :) thanks!

**Comment by lucassabreu** [comment]
> @lucassabreu v0.51.1 works great :) thanks!

i am glad to hear that
