### ISSUE TITLE
log command Request method 'GET' not supported

### ISSUE THREAD

**Issue by birchb1024** [lucassabreu/clockify-cli#29]
`$ clockify-cli --debug -t "$(pass clockify/api-key)" log
DEBUG 2020/06/16 00:25:23 Log - Date Param: 2020-06-16 00:00:00 +0000 UTC
DEBUG 2020/06/16 00:25:23 LogRange - First Date Param: 2020-06-16 00:00:00 +0000 UTC | Last Date Param: 2020-06-17 00:00:00 +0000 UTC
DEBUG 2020/06/16 00:25:23 Log Filter Params: Start: 2020-06-16T00:00:00Z, End: 2020-06-17T00:00:00Z
DEBUG 2020/06/16 00:25:30 url: https://api.clockify.me/api/v1/workspaces//user//time-entries?end=2020-06-17T00%3A00%3A00Z&hydrated=true&page=1&start=2020-06-16T00%3A00%3A00Z, status: 405, body: "{"message":"Request method 'GET' not supported","code":3000}"
Request method 'GET' not supported (code: 3000)
`

**Comment by lucassabreu** [comment]
hi @birchb1024, it looks like your are not setting the user id when calling the command... 

you can get it running this `curl`, and looking at the `id` field on the result:
```sh
curl -vs -H "X-Api-Key: $(pass clockify/api-key)" https://api.clockify.me/api/v1/user
```

i will improve the cli to not require the user-id, and assume the user id from token, but you can use the command like bellow, so you dont have to wait for me:

```sh
clockify-cli --debug -t "$(pass clockify/api-key)" --user-id "$YOUR_USER_ID" log
```

**Comment by lucassabreu** [comment]
@birchb1024 the new release should not require you to set the user id anymore

https://github.com/lucassabreu/clockify-cli/releases/tag/v0.5.0
