### ISSUE TITLE
snap: :53: socket: permission denied

### ISSUE THREAD

**Issue by alcarraz** [lucassabreu/clockify-cli#31]
Hi when using snap version of the app I get this:

```
clockify-cli config init --debug -i -u xxxx
? User Generated Token: ******

Get https://api.clockify.me/api/workspaces/: dial tcp: lookup api.clockify.me on [::1]:53: dial udp [::1]:53: socket: permission denied
```

Maybe you need to ask for some permission in snap package?

Thank you very much

**Comment by lucassabreu** [comment]
looks like it, i did the snap package just for fun, and was not maintaining it ... i will take a look as soon as i can

**Comment by alcarraz** [comment]
Ok thank you very much, will try with the released then

**Comment by lucassabreu** [comment]
hello @alcarraz, i released a new version on snapcraft, i am using it now, so it must be working again, you just need to update it.
