### ISSUE TITLE
Manual Mode Entry?

### ISSUE THREAD

**Issue by tkcranny** [lucassabreu/clockify-cli#40]
Love the tool, though it's not clear to me how (or if it's possible) to enter an entry _without_ starting a timer.

By that, I mean something like to:

```bash
$ clockify-cli manual -p $SOME_PROJECT -d $SOME_DESCRIPTION --start "13:00" --end "13:30"
```

Which will enter an entry like the "Manual Mode" possible from the Tracker page in the official UI

![image](https://user-images.githubusercontent.com/4208581/86677882-5c2ac180-c03f-11ea-99f4-ea63cf814c5d.png)

**Comment by lucassabreu** [comment]
there is no way using the parameters today, only if you use the interactive mode, than you can set the closing time

[![asciicast](https://asciinema.org/a/Xtp3hM9CNFOsPxdqANjBiDhSv.svg)](https://asciinema.org/a/Xtp3hM9CNFOsPxdqANjBiDhSv)

but i think i should add there options outside the interactive mode for script automation. 

as soon as i get the time i will take a look to create these options on `in` and `clone` sub-command
