### ISSUE TITLE
Feature Request: Allow starting timer with project name as well (instead of project id alone)

### ISSUE THREAD

**Issue by enigma0160** [lucassabreu/clockify-cli#42]
Currently, the `in` command requires the `project-id ` to start a time entry. This is difficult to use. Would it be possible to start the timer with the project name instead?

**Comment by lucassabreu** [comment]
i may implement this change in the future, for now what i do when i dont have a env var or similar with the project id is one of these:

```sh
clockify-cli in $(clockify-cli project list -n "<some part of the project name>" -q) "some description" 
```

or i use the interactive mode:
[![asciicast](https://asciinema.org/a/Xtp3hM9CNFOsPxdqANjBiDhSv.svg)](https://asciinema.org/a/Xtp3hM9CNFOsPxdqANjBiDhSv)

**Comment by enigma0160** [comment]
That should do for now. Thanks a lot for the quick reply and for this repo!

**Comment by lucassabreu** [comment]
hi @enigma0160, the version v0.10.0 now support name of the project as a valid parameter... to use it you need to use the flag `--allow-project-name`, or set the env var `CLOCKIFY_ALLOW_PROJECT_NAME` to `1`/`true`... 

or use the `clockify-cli config init`, it will then ask if you want to enable the function to all future calls.

**Comment by enigma0160** [comment]
Thank you!
