### ISSUE TITLE
Recommended Installation Mac OS X

### ISSUE THREAD

**Issue by spencerthayer** [lucassabreu/clockify-cli#56]
What way do you recommend installing this CLI for Mac OS X?

**Comment by lucassabreu** [comment]
for now i think there are two ways...

if you have `go` on your machine you could just run the following command: 
```sh
go get -u github.com/lucassabreu/clockify-cli
```

if you don't, than you can download the `clockify-cli_*_Darwin_i386.tar.gz` from the latest release

these are the options right now...

but looks like snapcraft could be used on mac, and it would be the best option, but i dont now if it works...

https://snapcraft.io/docs/install-snapcraft-on-macos

**Comment by lucassabreu** [comment]
@spencerthayer i was talking to my friend about using the snapcraft on mac... and a didn't know it required you to install a "mini-vm" to run it... so I added the option to use `brew` to install the client... if you could try it and tell me if it worked on your setup would be great

https://clockify-cli.netlify.app/#using-homebrew-https-brew-sh

**Comment by spencerthayer** [comment]
Cool!
