### ISSUE TITLE
Documentation doesn't show quick start 

### ISSUE THREAD

**Issue by stg101** [lucassabreu/clockify-cli#60]
It can be added to the readme or the official documentation, maybe provide an example. The most important steps are:

- clockify-cli config init
- clockify-cli project list
- clockify-cli in id description

Took me some time to understand this was the workflow.

**Comment by lucassabreu** [comment]
i will add it to the bucket list...

if you feel like it to open a pr with your "Getting Started" would really be good, an "outsider" view for this may be better than mine.

**Comment by stg101** [comment]
Sure, I'll work on this. :)

**Comment by stg101** [comment]
PR here https://github.com/lucassabreu/clockify-cli/pull/62
