### ISSUE TITLE
clockify-cli config init returns 'null'

### ISSUE THREAD

**Issue by khenriksson** [lucassabreu/clockify-cli#67]
Tried installing the client today using Homebrew (thank god I managed to find the getting started pr as well), but unfortunately I didn't come very far.

After installing I tried running `clockify-cli config init`, however, that returns `null`.

```
khenriksson@MacBook-Pro anecdotes % clockify-cli config init
null

```

Is this something that's supposed to happen? Also, init isn't mentioned in the clockify-cli available commands.

**Comment by lucassabreu** [comment]
i changed how some commands under config work... so to init the config you need to run `clockify-cli config --init` as a flag not argument...
