### ISSUE TITLE
implement task support

### ISSUE THREAD

**Issue by lucassabreu** [lucassabreu/clockify-cli#74]

**Comment by lockHrt** [comment]
Looking forward for better task support. Currently I need to visit the clockify website to set the task manually.

**Comment by lucassabreu** [comment]
hi @lockHrt i implemented the same features that [project selection has for the task](
https://github.com/lucassabreu/clockify-cli/releases/tag/v0.23.0), could you take a look if it helps you?

we dont use tasks here, so it kind wasn't a priority, but its done now.

you may need to run `clockify-cli config --init` to enable task listing on the output ;)

**Comment by lockHrt** [comment]
Hi, just checked latest version, interactive task chooser is working great. Thanks.
