### ISSUE TITLE
repeat most recent entry 

### ISSUE THREAD

**Issue by leosolid** [lucassabreu/clockify-cli#96]
is there a way to repeat the most recent entry when using `clockify-start in`? It'd be nice if there was a `--repeat` flag or something similar.

**Comment by lucassabreu** [comment]
hello @leosolid yes, you can copy a entry using `clockify-cli clone <entry-id>`, if you wanna copy the latest one (like the one you just closed), you can use the alias "last", would be:
```sh
clockify-cli clone last
```

**Comment by leosolid** [comment]
Can't believe I didn't see that in the `--help`. Thanks!
