### ISSUE TITLE
command to see current time-entry

### ISSUE THREAD

**Issue by hariseldon78** [lucassabreu/clockify-cli#98]
Hello. Is there a way to know the current "active" time entry, and if there is one?

**Comment by lucassabreu** [comment]
hi @hariseldon78 , you can use the command `clockify-cli log in-progress` and it should show the time entry you have active.

https://clockify-cli.netlify.app/en/commands/clockify-cli_log_in-progress/#clockify-cli-log-in-progress

if you don't have any the list will be empty.

**Comment by hariseldon78** [comment]
Oh great! Sorry i missed that.
